# Generated by Django 4.1.7 on 2023-04-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='symbol',
        ),
    ]
