# Generated by Django 4.1.7 on 2023-04-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_stock_currency_remove_stock_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
