# Generated by Django 4.1.7 on 2023-04-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_stock2_delete_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock2',
        ),
    ]
